version: 2
updates:
  - package-ecosystem: maven
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: "org.springframework.boot:spring-boot-starter-parent"
        update-types: ["version-update:semver-major"]
    groups:
      spring-boot-minor-patch:
        patterns:
          - "org.springframework.boot*"
        update-types:
          - "minor"
          - "patch"
      maven-other:
        patterns:
          - "*"
        exclude-patterns:
          - "org.springframework.boot*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      github-actions:
        patterns:
          - "*"
